version: '2'
services:

  verify:
    image: registry.jincor.com/backend/verify-develop:latest
    build:
        context: ./
        dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
      AUTH_API_URL: ${AUTH_API_URL}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAILGUN_SECRET: ${MAILGUN_SECRET}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
    ports:
      - "3000"
      - "4000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - redis

  redis:
    image: jincorcto/backend-redis:stable
    ports:
      - "6379"
